services:

  ekyc:

    build: .

    container_name: ekyc

    restart: unless-stopped

    ports:
      - "8000:8000"
      - "8501:8501"

    env_file:
      - .env

    volumes:

      - ./uploads:/app/uploads

      - ./logs:/app/logs

      - ./kyc.db:/app/kyc.db